### ISSUE TITLE
Running headless without watch hangs

### ISSUE THREAD

**Issue by roggan87** [aelbore/aria-vue#10]
I'm trying to run all tests headless without the watch-option, but I can't get it to work. Expected result would be to run all tests and exit with an error code if any tests fails. The actual result is that vite is started but no tests are run, and it won't terminate. I'm running it in the vs code terminal on Win 10.

Output:
```
> aria-vue -H



[vite] connecting...
[vite] connected.
(node:8944) UnhandledPromiseRejectionWarning: TimeoutError: waiting for function failed: timeout 60000ms exceeded
    at new WaitTask (C:\Users\rober\source\repos\tdd-vue3\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:482:34)
    at DOMWorld.waitForFunction (C:\Users\rober\source\repos\tdd-vue3\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:443:16)
    at Frame.waitForFunction (C:\Users\rober\source\repos\tdd-vue3\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:910:32)
    at Page.waitForFunction (C:\Users\rober\source\repos\tdd-vue3\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1291:33)
    at C:\Users\rober\source\repos\tdd-vue3\node_modules\aria-mocha\aria-mocha.js:418:128
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\rober\source\repos\tdd-vue3\node_modules\aria-mocha\aria-mocha.js:418:21
    at async Object.launch (C:\Users\rober\source\repos\tdd-vue3\node_modules\aria-mocha\aria-mocha.js:414:18)
    at async launchHeadless (C:\Users\rober\source\repos\tdd-vue3\node_modules\aria-vue\aria-vue.js:161:3)
    at async Server.<anonymous> (C:\Users\rober\source\repos\tdd-vue3\node_modules\aria-vue\aria-vue.js:171:16)
(node:8944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aelbore** [comment]
@roggan87 thanks for this I will take a look and get back to you

**Comment by roggan87** [comment]
@aelbore cool, thanks! Awesome work by the way. I've mostly played around so far with [this repository](https://github.com/JessicaSachs/vite-component-test-starter). The `headless` script in package.json, but without the -w option should replicate this issue.

**Comment by aelbore** [comment]
@roggan87 if you are using that repository in macosx and linux works fine, sure i tried find a way to test in windows

**Comment by roggan87** [comment]
@aelbore I'm not surprised Windows is the exception here. Tried to find any clues in the code on why this happens, but no success so far.

**Comment by aelbore** [comment]
@roggan87 Please see https://github.com/aelbore/vite-plugin-test
this is compatible for Vite 2.x
